### ISSUE TITLE
Add remaining models (or new ones)

### ISSUE THREAD

**Issue by Cervator** [Terasology/Oreons#1]
We currently have Oreon guards, builders, and the king. Originally Maternal had a few more types included:

https://forum.terasology.org/threads/candy-stuff.683/#post-6500

It would be nice to get those added in as well, and/or maybe add more varieties / teams. In the forum thread we talked about a different "flavor" (pun intended) based on the Haribo assorted licorice candy ;-)

Other colored versions could probably done by using the same models but overriding the texture?

I'll toss Maternal an email to see if he still has the original model files for the extras :-)
##

**Comment by mkienenb** [comment]
I was actually thinking the same thing about using the same models but
overriding the textures.
It was on my list of things to investigate.

On Fri, Jan 10, 2014 at 5:55 PM, Rasmus Praestholm <notifications@github.com

**Comment by jdrueckert** [comment]
Split into separate tickets to allow for easier task pick up and completion:
- #9 - Flag Carrier
- #10 - Queen/Princess
- #11 - Torch Guard
- #12 - Baby Oreon
- #13 - Heavy Guard
