### ISSUE TITLE
King is oddly tiny

### ISSUE THREAD

**Issue by Cervator** [Terasology/Oreons#2]
In-game the king model is much smaller than the others, which I don't think is intentional based on the original sketch:

http://forum.movingblocks.net/threads/candy-stuff.683/#post-6500

Probably exported funny :)

However, I'm not sure we actually have the original blend file. Maternal's original work is sitting in Google Drive and I don't see that one: https://docs.google.com/folderview?id=0B8Kq9XFiF6gxU1dRMlcxeWstRzA
##

**Comment by jdrueckert** [comment]
Can't reproduce anymore: King is the same size as the guard.
![image](https://user-images.githubusercontent.com/29981695/94986251-7bad8980-055d-11eb-862c-66ae813c85f9.png)
